[package]
name = "rust-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = "1.0.219"
serde_json = "1.0.141"
tokio = { version = "1.47.0", features = ["full"] }
utoipa = "5.4.0"
