version: "3.9"

services:
  mysql:
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: rsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command:
      - --log-bin-trust-function-creators=1
    restart: always
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
